### ISSUE TITLE
Multiple MQTT topics

### ISSUE THREAD

**Issue by chatmurai** [plapointe6/CustomHADevicesCollection#2]
Let's say I want my ESP8266 device to handle not one but two or more MQTT topics so that I can use the others GPIOs on the board to drive more lights. I understand I can publish or subscribe to any topic, but I can't figure out how to handle the command or state name. 
I can't just duplicate `client.subscribe(light.getCommandTopic(), [](const String &payload) {});` handler because this way it's impossible to specify which command to listen to or to publish to.

I don't know if I sound clear on this one, I am kind of lost.

**Comment by plapointe6** [comment]
You could try something like this to handle two lights : 

```c++
#include "EspMQTTClient.h"
#include "HAMqttDevice.h"
#include <ESP_EEPROM.h>

// MQTT client setup
EspMQTTClient client(
  "mySSID",         // Wifi ssid
  "myPassword",     // Wifi password
  "192.168.1.101",  // MQTT broker ip
  "myUsername",     // MQTT username
  "myMQTTPassword", // MQTT password
  "my_light"        // MQTT Client name
);

// Home Assitant device creation for MQTT discovery
HAMqttDevice light1("My First Nice Lamp ", HAMqttDevice::LIGHT);
HAMqttDevice light2("My Second Nice Lamp ", HAMqttDevice::LIGHT);

// Pin assignation
const int relay1Pin = D1, relay2Pin = D2;

// Current status of the light
struct lighValues {
	bool light1On = false;
	bool light2On = false;
}

void setup() 
{
  //Serial.begin(115200);
  
  pinMode(relay1Pin, OUTPUT);
  pinMode(relay2Pin, OUTPUT);

  // Charge saved values from eeprom
  EEPROM.begin(sizeof(lighValues));
  if(EEPROM.percentUsed() >= 0)
    EEPROM.get(0, lighValues);
  
  // Setup the parameters of the device for MQTT discovery in HA
  light1.enableAttributesTopic();
  light2.enableAttributesTopic();

  client.enableHTTPWebUpdater();
  //client.enableDebuggingMessages();
}

void onConnectionEstablished()
{
  // Subscribe to the command topic ("cmd_t") of this device.
  client.subscribe(light1.getCommandTopic(), [] (const String &payload)
  {
	....
  });
  
   client.subscribe(light2.getCommandTopic(), [] (const String &payload)
  {
	....
  });
  
  // Subscribe to Home Assitant connection status events.
  client.subscribe("ha/status", [] (const String &payload)
  {
    // When the status of Home assistant get online, publish the device config
    if (payload.equals("online"))
    {
      client.publish(light1.getConfigTopic(), light1.getConfigPayload());
      client.publish(light2.getConfigTopic(), light2.getConfigPayload());
      
      // After sending the device config to HA, wait a little to allow HA to create the entity.
      client.executeDelayed(5 * 1000, []() {

        // Send the current state of the light
        client.publish(light1.getStateTopic(), lighValues.light1On ? "ON" : "OFF");
        client.publish(light2.getStateTopic(), lighValues.light2On ? "ON" : "OFF");
        
		....
      });
    }
  });
}

void loop() 
{
  client.loop();

  if(lighValues.light1On)
    digitalWrite(relay1Pin, HIGH);
  else
    digitalWrite(relay1Pin, LOW);

....
}
```

Disclaimer: I made this example very fast without checking if there is errors.

**Comment by chatmurai** [comment]
Thanks for your answer. 
light1 is detected by Home Assistant, but light2 isn't. I may have made a mistake but I can't see it...
Following your advice, this is the code i ended up with (sorry for the length) : 

``` c++
#include <Arduino.h>
#include "EspMQTTClient.h"
#include "HAMqttDevice.h"
#include <ESP_EEPROM.h>

// MQTT client setup
EspMQTTClient client(
    "************",      // Wifi ssid
    "************",      // Wifi password
    "************",      // MQTT broker ip
    "************",      // MQTT username
    "************",      // MQTT password
    "auto_discovery_test_lights" // MQTT Client name
);

// Home Assitant device creation for MQTT discovery
HAMqttDevice light1("auto-discovery-light-1", HAMqttDevice::LIGHT);
HAMqttDevice light2("auto-discovery-light-2", HAMqttDevice::LIGHT);

// Pin assignation
const int light1Pin = D0;
const int light2Pin = D1;

// Current status of the light
struct LightValues
{
  bool light1On;
  bool light2On;
};
struct LightValues lightValues = {false, false};

void setup()
{
  Serial.begin(115200);

  pinMode(light1Pin, OUTPUT);
  pinMode(light2Pin, OUTPUT);

  // Charge saved values from eeprom
  EEPROM.begin(sizeof(lightValues));
  if (EEPROM.percentUsed() >= 0)
    EEPROM.get(0, lightValues);

  // Setup the parameters of the device for MQTT discovery in HA
  light1.enableAttributesTopic();
  light2.enableAttributesTopic();

  client.enableHTTPWebUpdater();
  client.setMaxPacketSize(512);
  client.enableDebuggingMessages();
}

void onConnectionEstablished()
{
  // Subscribe to the command topic ("cmd_t") of this device for light1
  client.subscribe(light1.getCommandTopic(), [](const String &payload) {
    // Turn the light on/off depending on the command received from Home Assitant
    if (payload.equals("ON"))
      lightValues.light1On = true;
    else if (payload.equals("OFF"))
      lightValues.light1On = false;

    // Confirm to Home Assitant that we received the command and updated the state.
    // HA will then update the state of the device in HA
    client.publish(light1.getStateTopic(), payload);

    // Save the new state in memory
    EEPROM.put(0, lightValues.light1On);
    EEPROM.commit();
  });

  // Subscribe to the command topic ("cmd_t") of this device for light2
  client.subscribe(light2.getCommandTopic(), [](const String &payload) {
    // Turn the light on/off depending on the command received from Home Assitant
    if (payload.equals("ON"))
      lightValues.light2On = true;
    else if (payload.equals("OFF"))
      lightValues.light2On = false;

    // Confirm to Home Assitant that we received the command and updated the state.
    // HA will then update the state of the device in HA
    client.publish(light2.getStateTopic(), payload);

    // Save the new state in memory
    EEPROM.put(0, lightValues.light2On);
    EEPROM.commit();
  });

  // Subscribe to Home Assitant connection status events.
  client.subscribe("ha/status", [](const String &payload) {
    // When the status of Home assistant get online, publish the device config
    if (payload.equals("online"))
    {
      client.publish(light1.getConfigTopic(), light1.getConfigPayload());
      client.publish(light2.getConfigTopic(), light2.getConfigPayload());

      // After sending the device config to HA, wait a little to allow HA to create the entity.
      client.executeDelayed(5 * 1000, []() {
        // Send the current state of the light
        client.publish(light1.getStateTopic(), lightValues.light1On ? "ON" : "OFF");
        client.publish(light2.getStateTopic(), lightValues.light2On ? "ON" : "OFF");

        // Send the IP address of the device to HA
        light1
            .clearAttributes()
            .addAttribute("IP", WiFi.localIP().toString());

        light2
            .clearAttributes()
            .addAttribute("IP", WiFi.localIP().toString());

        client.publish(light1.getAttributesTopic(), light1.getAttributesPayload());
        client.publish(light2.getAttributesTopic(), light2.getAttributesPayload());
      });
    }
  });
}

void loop()
{
  client.loop();

  if (lightValues.light1On)
    digitalWrite(light1Pin, LOW);
  else
    digitalWrite(light1Pin, HIGH);

  if (lightValues.light2On)
    digitalWrite(light2Pin, LOW);
  else
    digitalWrite(light2Pin, HIGH);
}
```

I found out that HA raises an error regarding the discovery of the second topic :

```
2021-04-21 12:01:27 DEBUG (MainThread) [homeassistant.components.mqtt] Received message on ha/light/auto-discovery-light-1/config: b'{"~":"ha/light/auto-discovery-light-1","name":"auto-discovery-light-1","cmd_t":"~/cmd","stat_t":"~/state","json_attr_t":"~/attr"}'
2021-04-21 12:01:27 DEBUG (MainThread) [homeassistant.components.mqtt.discovery] Process discovery payload {'name': 'auto-discovery-light-1', 'command_topic': 'ha/light/auto-discovery-light-1/cmd', 'state_topic': 'ha/light/auto-discovery-light-1/state', 'json_attributes_topic': 'ha/light/auto-discovery-light-1/attr', 'platform': 'mqtt'}
2021-04-21 12:01:27 INFO (MainThread) [homeassistant.components.mqtt.discovery] Component has already been discovered: light auto-discovery-light-1, sending update
2021-04-21 12:01:27 INFO (MainThread) [homeassistant.components.mqtt.mixins] Got update for entity with hash: ('light', 'auto-discovery-light-1') '{'name': 'auto-discovery-light-1', 'command_topic': 'ha/light/auto-discovery-light-1/cmd', 'state_topic': 'ha/light/auto-discovery-light-1/state', 'json_attributes_topic': 'ha/light/auto-discovery-light-1/attr', 'platform': 'mqtt'}'
2021-04-21 12:01:27 INFO (MainThread) [homeassistant.components.mqtt.mixins] Ignoring unchanged update for: light.auto_discovery_light_1
2021-04-21 12:01:27 DEBUG (MainThread) [homeassistant.components.mqtt.discovery] Pending discovery for ('light', 'auto-discovery-light-1'): deque([])
2021-04-21 12:01:27 DEBUG (MainThread) [homeassistant.components.mqtt] Received message on ha/light/auto-discovery-light-2/config: b'{"~":"ha/light/auto-discovery-light-2","name":"auto-discovery-light-2"}'
2021-04-21 12:01:27 DEBUG (MainThread) [homeassistant.components.mqtt.discovery] Process discovery payload {'name': 'auto-discovery-light-2', 'platform': 'mqtt'}
2021-04-21 12:01:27 INFO (MainThread) [homeassistant.components.mqtt.discovery] Found new component: light auto-discovery-light-2
2021-04-21 12:01:27 ERROR (MainThread) [homeassistant.util.logging] Exception in async_discover when dispatching 'mqtt_discovery_new_light_mqtt': ({'name': 'auto-discovery-light-2', 'platform': 'mqtt'},)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/mqtt/mixins.py", line 160, in async_discover
    config = schema(discovery_payload)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/validators.py", line 218, in __call__
    return self._exec((Schema(val) for val in self.validators), v)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/validators.py", line 341, in _exec
    raise e if self.msg is None else AllInvalid(self.msg, path=path)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/validators.py", line 337, in _exec
    v = func(v)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 817, in validate_callable
    return schema(data)
  File "/usr/src/homeassistant/homeassistant/components/mqtt/light/__init__.py", line 26, in validate_mqtt_light
    return schemas[value[CONF_SCHEMA]](value)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 594, in validate_dict
    return base_validate(path, iteritems(data), out)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 432, in validate_mapping
    raise er.MultipleInvalid(errors)
voluptuous.error.MultipleInvalid: required key not provided @ data['command_topic']
2021-04-21 12:01:27 DEBUG (MainThread) [homeassistant.components.mqtt.discovery] Pending discovery for ('light', 'auto-discovery-light-2'): deque([])
2021-04-21 12:01:32 DEBUG (MainThread) [homeassistant.components.mqtt] Received message on ha/light/auto-discovery-light-1/state: b'OFF'
2021-04-21 12:01:32 DEBUG (MainThread) [homeassistant.components.mqtt] Received message on ha/light/auto-discovery-light-1/attr: b'{"IP":"192.168.10.64"}'
```

**Comment by chatmurai** [comment]
Sorry to flood this thread, but I might get a clue of what is happening. Here is the ESP log : 
```
WiFi: Connecting to ************ ... (0.917000s) 
WiFi: Connected (4.871000s), ip : ************ 
WEB: Updater ready, open http://auto_discovery_lights.local in your browser and login with username '************' and password '************'.
MQTT: Connecting to broker "************" with client name "auto_discovery_lights" ... (5.378000s) - ok. (6.889000s) 
MQTT: Subscribed to [ha/light/auto-discovery-light-1/cmd]
MQTT: Subscribed to [ha/light/auto-discovery-light-2/cmd]
MQTT: Subscribed to [ha/status]
MQTT >> [ha/status] online
MQTT << [ha/light/auto-discovery-light-1/config] {"~":"ha/light/auto-discovery-light-1","name":"auto-discovery-light-1","cmd_t":"~/cmd","stat_t":"~/state","json_attr_t":"~/attr"}
MQTT << [ha/light/auto-discovery-light-2/config] {"~":"ha/light/auto-discovery-light-2","name":"auto-discovery-light-2"}
MQTT << [ha/light/auto-discovery-light-1/state] OFF
MQTT << [ha/light/auto-discovery-light-2/state] OFF
MQTT << [ha/light/auto-discovery-light-1/attr] {"IP":"192.168.10.64"}
MQTT << [ha/light/auto-discovery-light-2/attr] {"IP":"192.168.10.64"}
```
If you look closely you can see that light1 discovery topic is well formed, while light2 one is not, it lacks the payload part `"cmd_t":"~/cmd","stat_t":"~/state","json_attr_t":"~/attr"`

**Comment by plapointe6** [comment]
Thanks for these logs. There definitely something odd happening. Your code seems fine. I will do some testing with your code to find what going on. Meanwhile, if you want to do some testing, you could try outputting ```Serial.print(light2.getConfigPayload())``` at different places in your code to ensure that what it is sent via MQTT is the same thing that getConfigPayload() generate.

**Comment by chatmurai** [comment]
Anywhere I put `Serial.print(light2.getConfigPayload())` I get `{"~":"ha/light/auto-discovery-light-2","name":"auto-discovery-light-2"}` with only the first part of the payload.
I am far from being an expert in C programming and I learned OOP a long time ago width ActionScript :sigh: , but I had a look in HAMqttDevice.cpp and something called my attention in the `enableAttributesTopic` method :
```
static bool firstCall = true;

    if(firstCall)
    {
        addConfigVar("json_attr_t", "~/attr");
        firstCall = false;
    }
```
If I ask the class to generate two HAMqttDevice instances like I do, won't this var prevents the second (and the next) instance to be properly populated with attributes ?

**Comment by plapointe6** [comment]
You are completely right :100:

**Comment by plapointe6** [comment]
Could you try with the new version (1.2.0) of HAMqttDevice please? 
https://github.com/plapointe6/HAMqttDevice/releases/tag/1.2.0

**Comment by chatmurai** [comment]
Thanks a lot it works !
But something is odd in HA  : the first light is seen as a Light integration but the second one appears as an MQTT integration : 
![snapshot](https://user-images.githubusercontent.com/1504536/115568546-b1794c00-a2bc-11eb-91e3-3bb417afbd5f.png)

**Comment by plapointe6** [comment]
Is the configuration payload is the same for the two lights?

**Comment by chatmurai** [comment]
Yes it is but after a HA restart the two are MQTT type... which is weird because I can change their unique id which is not supposed to be allowed with auto discovery entities, but not a big deal imho
![snap2](https://user-images.githubusercontent.com/1504536/115569681-c0143300-a2bd-11eb-9ad6-f82c052d8d06.png)

**Comment by plapointe6** [comment]
Ok, my devices are associated with the right integration. If you find out why it is not the case for you, I am interested to know :)
![image](https://user-images.githubusercontent.com/6698328/115570777-65aeae80-a28c-11eb-8dda-e8c1802b5b6e.png)

**Comment by chatmurai** [comment]
I'll have a look at this this evening and I'll let you know if I find something. Thanks again for your time and your work !

**Comment by chatmurai** [comment]
Well I had some time to add a third topic but it is shown as an MQTT device too. long story short, it works...
![snap3](https://user-images.githubusercontent.com/1504536/115720402-53606d80-a37d-11eb-8699-158d0cce47d8.png)
